<?php

namespace Database\Seeders;

use App\Models\BarcodeToken;
use Illuminate\Database\Seeder;

class BarcodeTokenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('🌱 Seeding Barcode Tokens...');

        // Create one universal barcode token for all equipment
        $token = BarcodeToken::create([
            'equipment_type' => 'all',
            'is_active' => true,
            // token will be auto-generated by model's boot method
        ]);

        $this->command->info('✅ Barcode Token created successfully!');
        $this->command->info('');
        $this->command->info('=== BARCODE TOKEN DETAILS ===');
        $this->command->info('Token: ' . $token->token);
        $this->command->info('Equipment Type: ' . $token->equipment_type);
        $this->command->info('Status: ' . ($token->is_active ? 'Active' : 'Inactive'));
        $this->command->info('');
        $this->command->info('📱 Scan URL: ' . url('/barcode/wo/' . $token->token));
        $this->command->info('');
        $this->command->info('💡 Tip: Use this token to generate QR code in Filament panel');
    }
}
