<?php

namespace App\Filament\Resources\PmCompliances;

use App\Filament\Resources\PmCompliances\Pages\CreatePmCompliance;
use App\Filament\Resources\PmCompliances\Pages\EditPmCompliance;
use App\Filament\Resources\PmCompliances\Pages\ListPmCompliances;
use App\Filament\Resources\PmCompliances\Schemas\PmComplianceForm;
use App\Filament\Resources\PmCompliances\Tables\PmCompliancesTable;
use App\Models\PmCompliance;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;

class PmComplianceResource extends Resource
{
    protected static ?string $model = PmCompliance::class;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedChartBar;
    
    protected static ?string $navigationLabel = 'PM Compliance';
    
    protected static ?int $navigationSort = 5;
    
    public static function canCreate(): bool
    {
        return false; // Read-only, auto-generated by scheduled task
    }
    
    public static function canEdit($record): bool
    {
        return false; // Read-only
    }
    
    public static function canDelete($record): bool
    {
        return false; // Read-only
    }
    
    public static function canAccess(): bool
    {
        $user = \Illuminate\Support\Facades\Auth::user();
        return $user && in_array($user->role, ['super_admin', 'manager', 'asisten_manager']);
    }
    
    public static function getNavigationGroup(): ?string
    {
        return 'PM Management';
    }

    public static function form(Schema $schema): Schema
    {
        return PmComplianceForm::configure($schema);
    }

    public static function table(Table $table): Table
    {
        return PmCompliancesTable::configure($table);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListPmCompliances::route('/'),
        ];
    }
}
